# Generated by Django 5.1.1 on 2024-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cinema/images/person/photos/')),
                ('role', models.CharField(blank=True, choices=[('actor', 'Актер'), ('director', 'Режисер')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField()),
                ('budget', models.PositiveIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='cinema/images/movies/posters/')),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre')),
                ('actors', models.ManyToManyField(related_name='acted_in_movies', to='cinema.movieperson')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='cinema.movieperson')),
            ],
        ),
    ]
